### ISSUE TITLE
Compatibility to awesome-pages

### ISSUE THREAD

**Issue by neatc0der** [zayd62/mkdocs-versioning#59] opened 2021-01-15 16:17 UTC
**Describe the bug**
When using the "Rest" feature of [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/), an `AttributeError` occurs in [entry.py:47](https://github.com/zayd62/mkdocs-versioning/blob/387ccd966289bf142fd45df94110a43766867a10/mkversion/entry.py#L47):
> `AttributeError: 'str' object has no attribute 'keys'`

As you can see, the ellipsis within the `nav` section (see below) causes the error.

**To Reproduce**
1. In addition to `mkdocs` and `mkdocs-versioning`, please install `mkdocs-awesome-pages-plugin`
2. Use `mkdocs.yml`:
```yaml
site_name: Sample Project
nav:
  - Home: index.md
  - ...
  - "Version Selector": "../"
plugins:
  - search
  - mkdocs-versioning:
      version: "1.0"
  - awesome-pages
```
3. Run `mkdocs build`

**Expected behavior**
The error should not occur.

**Additional context**
This error is independent of package versions, OS and other external factors.

**Comment by zayd62** [comment] 2021-01-24 12:59
hey thanks for the bug report. i also noticed that you provided a fix in #60  which is really helpful :+1:. 

i was hoping the plugin design would make the plugin work regardless of whatever plugins/themes were installed but since awesome-pages is related to the nav which my plugin also uses, i guess a bug would've been inevitable. thanks for the fix as well. will close this issue once i've merged your changes into master and write some additional documentation

**Comment by zayd62** [comment] 2021-01-30 13:25
hey @neatc0der so i took at #63 and after merging, i noticed that when running `mkdocs serve`, the code seems to remove the first nav element. i've managed to narrow it down to these lines https://github.com/zayd62/mkdocs-versioning/blob/4fc89254808f3aa61158f169ad0a42e508137447/mkversion/entry.py#L44-L49

if i comment it out, it doesnt seem to affect functionality but im not sure how is effect awsome-pages. if you could take a look that would be great as im unfamiliar with the plugin and dont have a lot of time on my hands at the moment to figure it out myself so if  you could do that, it would be greatly appreciated

**Comment by neatc0der** [comment] 2021-01-30 19:55
Ok, so my contribution to your project does not meet my own expectations on quality at all. Though, during review of what I did there, I found this commit which doesn't seem to make sense:
https://github.com/zayd62/mkdocs-versioning/commit/fdf3147a14d6eded3575ed878bea05db2082ef65#diff-c7e9607b82010759499e47b73af2b3cf456f46d55cf69f69e5e38aa2098d98ccL48

Can you help me out here? What was your intention to replace the configuration parameter with?

**Comment by zayd62** [comment] 2021-01-31 11:03
so https://github.com/zayd62/mkdocs-versioning/commit/fdf3147a14d6eded3575ed878bea05db2082ef65#diff-c7e9607b82010759499e47b73af2b3cf456f46d55cf69f69e5e38aa2098d98ccL48 appeared in https://github.com/zayd62/mkdocs-versioning/commit/94613ad68b4fa721d532283637f67cfbeeb014ae# (committed 16 jun 2020)

it appears that serving was broken so i had to check if i was serving, if i was, then i remove the `version selector` from the navigation and then let it serve. i cant remember why i wrote that in the first place but perhaps there was a bug in mkdocs as i updated `requirements.txt` on 27 jun 2020 https://github.com/zayd62/mkdocs-versioning/commit/69d926503af66b79df90f77d172fa8808aa05199 

looking at mkdocs changelog, it appears that there was a bug with serving https://www.mkdocs.org/about/release-notes/#version-111-2020-05-12 so it could be that but since the serving check was introduced last june, i have no idea why it was written. 

so i guess the answer to your question `What was your intention to replace the configuration parameter with?` is either 

1. fix a bug with mkdocs
2. maybe i didnt want the `version selector` to appear in the nav
3. no idea

I can safely comment this code out which is a mix of your additions and mine and the plugin works as intended so all that is left is compatibility with awesome-pages

https://github.com/zayd62/mkdocs-versioning/blob/4fc89254808f3aa61158f169ad0a42e508137447/mkversion/entry.py#L44-L49

**Comment by neatc0der** [comment] 2021-02-10 22:06
I agree with answer N°3 😄 

Sounds good to me, so I'm open to a new release! Thanks for your support.

**Closed as completed** 2021-02-11 10:23 UTC
Labels: bug

**Comment by zayd62** [comment] 2021-02-11 10:28
available on pypi. hopefully this fixes everything. thanks for the help :+1:
